{
    "data": {
        "amount": 50000,
        "authorization": {
            "account_name": None,
            "authorization_code": "AUTH_txru6za45h",
            "bank": "TEST BANK",
            "bin": "408408",
            "brand": "visa",
            "card_type": "visa ",
            "channel": "card",
            "country_code": "NG",
            "exp_month": "12",
            "exp_year": "2030",
            "last4": "4081",
            "receiver_bank": None,
            "receiver_bank_account_number": None,
            "reusable": True,
            "signature": "SIG_suTOe0sjN1wdQZ0UPWMF",
        },
        "channel": "card",
        "created_at": "2024-03-06T16:10:19.000Z",
        "currency": "NGN",
        "customer": {
            "customer_code": "CUS_1cfmuy7f3m7bk2l",
            "email": "test@beans.com",
            "first_name": "jhggjhg",
            "id": 161154284,
            "international_format_phone": None,
            "last_name": "jknhj",
            "metadata": None,
            "phone": "",
            "risk_action": "default",
        },
        "domain": "test",
        "fees": 750,
        "fees_breakdown": None,
        "fees_split": None,
        "gateway_response": "Successful",
        "id": 3607268736,
        "ip_address": "197.210.53.111",
        "log": None,
        "message": None,
        "metadata": {"referrer": "https://paystack.com/pay/qek41k4sbz"},
        "order_id": None,
        "paidAt": "2024-03-06T16:10:22.000Z",
        "paid_at": "2024-03-06T16:10:22.000Z",
        "plan": {},
        "pos_transaction_data": None,
        "reference": "T959153988755625",
        "requested_amount": 50000,
        "source": {
            "entry_point": "request_inline",
            "identifier": None,
            "source": "checkout",
            "type": "web",
        },
        "split": {},
        "status": "success",
        "subaccount": {},
    },
    "event": "charge.success",
}
